# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=26
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XQYtNhSRs+yO1MMUA0h+DolWI/eYE7MYAXK/JjXNKZniMKDP8vw7ceHIAPFcinat6H6Hu5V+95+pjOm1YvyF+YLd8tGmyTUk5DgYwQQrZtV+isReGps78tXe032o46LGUKm3CRzrk4+CLzFHyRZCElZfki445HwkiSGX1qU4XlNVcoryEamGHHnN5A4KysC8wH6FrhLSOLdxSMfFA7O3OJa3sk7EtYIJvyeC22qredkBHjCGEO+1c26g7fEiB/Ye30DXL5WnX4ZB/N6jGIzTW+0QJdKGdhYEPfLGe9c3SofIEUXNUUtQ+m0nJDP1MTnLECDqUf8q3wtSHERXp44lzFw3q3BfDYV8TOpgrTOrcvro47hYCBgs7DxMnM7snCcgzzucKkkls37c+0K5ek2yJLW5fYnVRFkX+ugqIZXJGSnI2Rz1/IPDb/1+POTrb42sR3XDoII/38uXl0uyGpeeUnhECRTPndR8YXEUaj8gaf6GAglINm+P2Ec8biYMxsiYTg9oXEwfhasADlCDJelO0OIoj0unGkwfbWw5NFKaR3TDnuxOiFINFRtqgav31rjp18+n2vwZYmcbYTf/kbUMsStHtGbrPYyiMZ1yJw7cwXLTJERTTQYAmkFMIZGRjXDzBlkleXvoEt3um1KkxN6KkQaeM3n1uD8oy79ZN2NCJMg="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
