travis:
  secure:
    BINSTAR_TOKEN: bos6UpF9ajv2PWpu38OiG0iVnFdtfQgPad1Fvz9BzHZBCZfM6qNVxP+O0HrXCp+oop41Ib6jAZ+IBx/joqJ9dtoK2WFfL3jkCPh/5hAahqOAPWWeYDxKWe/FRFO3Kf1KjIqfp+qWKEbvMwZXok2imMGxqVkB5zLXlCyHJDwCQM4LxapSqdXuGWaLEffnHUu9xglGYp9YhaBzTL3xmUNYM4JsXhGIXUXqajaPj7cecQdBf8IwFLnQrBXKinDHfIOyyFUEzNIThdE6+25cZIF09E3D/gUcDX9DU6+kV/6zdlt32XZmMdn1xzwtFodY5czU0kpMSC/AjbXFjzQA0HN53jb7N7QHrFPJLCUkBLBnYkkLQ4lk1iGbSwdVwaAm2pdzEsMZgnyHf9PWoaww8xdAhC2+hx1+MWA2GwQ17Nn7fioh5pKR5FZnAyzHRqCDslXXkqA8oehYR4YJ7AJEYJMpO5xn7+CPk4B3brjkvs8Y7+P2RZWo9IqRQX8jEp2vy6HIcRpI9sAA5aPzqVwoWPyxnf33wMltG9HAGf06Few3/UR6tdl74X4mT5k5HuHIEyPpjQWZ19XG3DWeZjzJvPJu7tyL/80lkMFgCgPG0troPBkisnQaIwXehITMS2glMwJba+DIamtYLf5yCK2q4gS4FLE+RnjAn/by6mo1O9vIfa0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
