travis:
  secure:
    BINSTAR_TOKEN: qsh1xxS2Q1WHROPC6+t/lrBlNiJFICMJqBwLwEUKRcXMSoCM/WGrflpnGy2RCjeryUZucHshIZdRu/7XzFCxBx4LxD0o1yKYqQeU3QUW+bRmPvCEMvqrREqeQrX0hGA6G2MFBsAYOdpXVS7B8kNg5pQ4rl+eYglGSV5CG5drljdlxzOBXQUjD21jomss3Nbv9lf/FGYvWwO4Ko6vIH1S7027W0WJqUql2HrFrcz2OgxRz6xTPXdFudSb1/rdzluzo90gWJoVNt9qXSMDdB/dY+qRNPrnaW0nQ9FHVzNuH1GuY3UfoRGfjYteXA9TUGXboPd8xUUMdUxJYMBYYYgSHkKRtdrbllFVWe/mmeOVZZYp1hfFt1WW2cWQKlu3QXTxfHdXyX8SRX6YcazLjl9BpW2/H8Jul3ToFKKXqwcUAkMym0g//cnCfjsk4qI3/pdkDbSdgVbTg1o4gRUjjxNtDoFnO556TA9eFCtJoqLVifB5vCtkyLzbTKNQjs3S5FY5oFXbvic1aB5hlziV/OiBKwVyEXIMisTwcDjRU0B4JM+1IHVKYdDElcM7stTVjEoS4p2bgAWiVRNDeGScbIZcUktM57PP3ZTJUYJoaHZ5RDToSo/7UIw1hhH+GjuKO7WdiIxCYZxcs3CF3OURYgJjmZluADD7GbD8Ze+LnAYSvNE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
