travis:
  secure:
    BINSTAR_TOKEN: XQYtNhSRs+yO1MMUA0h+DolWI/eYE7MYAXK/JjXNKZniMKDP8vw7ceHIAPFcinat6H6Hu5V+95+pjOm1YvyF+YLd8tGmyTUk5DgYwQQrZtV+isReGps78tXe032o46LGUKm3CRzrk4+CLzFHyRZCElZfki445HwkiSGX1qU4XlNVcoryEamGHHnN5A4KysC8wH6FrhLSOLdxSMfFA7O3OJa3sk7EtYIJvyeC22qredkBHjCGEO+1c26g7fEiB/Ye30DXL5WnX4ZB/N6jGIzTW+0QJdKGdhYEPfLGe9c3SofIEUXNUUtQ+m0nJDP1MTnLECDqUf8q3wtSHERXp44lzFw3q3BfDYV8TOpgrTOrcvro47hYCBgs7DxMnM7snCcgzzucKkkls37c+0K5ek2yJLW5fYnVRFkX+ugqIZXJGSnI2Rz1/IPDb/1+POTrb42sR3XDoII/38uXl0uyGpeeUnhECRTPndR8YXEUaj8gaf6GAglINm+P2Ec8biYMxsiYTg9oXEwfhasADlCDJelO0OIoj0unGkwfbWw5NFKaR3TDnuxOiFINFRtqgav31rjp18+n2vwZYmcbYTf/kbUMsStHtGbrPYyiMZ1yJw7cwXLTJERTTQYAmkFMIZGRjXDzBlkleXvoEt3um1KkxN6KkQaeM3n1uD8oy79ZN2NCJMg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
